### ISSUE TITLE
Additional improvements to consider for OFEP

### ISSUE THREAD

**Issue by Amit0617** [open-feature/ofep#55]
```[tasklist]
### Tasks
- [x] Need a document covering process of creating a new proposal
- [x] Need a header to specify the category of proposal
- [ ] Need a state to specify stale kind of proposals from author side.
```

**Comment by Amit0617** [comment]
@beeme1mr

**Comment by Amit0617** [comment]
Well... why not?

**Comment by beeme1mr** [comment]
Hey @Amit0617, sorry for the delay. I'm thinking we should consider the ideal end to end flow.

In my opinion, it would look something like this:

1. A contributor has an idea for a new feature they think should be in OpenFeature
2. They navigate to the OFEP repo and review the readme. The readme should have a section that explicitly states when an OFEP should be created. I think the "[Is My Thing an Enhancement?](https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement)" section of the Kubernetes enhancements repo does a nice job.
3. Next, the contributor would create an issue. We could use an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) to ensure we always get the key information we need to notify the correct people.
4. The issue would then need some level of support by the OpenFeature community and leadership to move to the next stage.
5. From there, a template or some kind of generator could be used to create the OFEP itself. The OFEP would be included in a PR that references the previously agreed upon issue.
6. Automation should ensure that the appropriate people are added to the review and that the PR doesn't become stale.
7. Once a decision is made, the OFEP status would be updated to approved, withdrawn, ect and the PR would be merged. It's important that even rejected PRs are not discarded so that future contributes can understand why a decision was or wasn't made.
8. Finally, the OFEP published somewhere so that it's easy to discover and reference at a later point.

I realize there are a few hand wavy items in there like "ensure that the appropriate people are added". I believe those are solvable problems once the core workflow is agreed upon.

@AlexsJones, what do you think? Is this more or less what you had in mind?

**Comment by Amit0617** [comment]
> I realize there are a few hand wavy items in there like "ensure that the appropriate people are added".
I can see one way to achieve that by picking the people who were engaged in the issue referenced by PR.

**Comment by Amit0617** [comment]
Issue template form for the 3rd point mentioned by @beeme1mr 

Also, I can't see the discussion section in the repository. Is this intentional as we want to discuss everything in the comments for respective issues or PRs for proposal? Otherwise there could be a section in the form to provide the link for the discussion thread initiated by proposal author.
