### ISSUE TITLE
Assign reviewers automatically based on topic

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/ofep#72]
```[tasklist]
### Tasks
- [x] Set reviewers on GitHub issue
- [ ] Set reviewers on GitHub Pull Request
- [ ] Document how the review assignee process works
```

**Comment by beeme1mr** [comment]
There's a GitHub Action that sets reviewers based on an issue body.
