### ISSUE TITLE
Publish OFEPs to a website that’s searchable.

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/ofep#76]
```[tasklist]
### Tasks
- [ ] Publish OFEPs to a GitHub page
- [ ] Automatically publish when an OFEP PR has been merged
- [ ] Extend OFEPs to include useful metadata (e.g. status, component, author)
- [ ] Each OFEP can be linked to directly
```

**Comment by mihirm21** [comment]
https://ofep-testing.readthedocs.io/    please check this website. 
Its repo is: https://github.com/mihirm21/ofep-testing
